apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-book-catalog
  labels: 
    env: test
spec:
  replicas: 
  selector:
    matchLabels:
      env: test  
  template:
    metadata:
      labels: 
        env: test
    spec:
      volumes:
        - name: configmap-book-catalog-volume
          configMap: 
                name: configmap-book-catalog
      containers:
        - name:  test-book-catalog
          image: montud/test-book-catalog:latest
          env:
            - name: DATASOURCEURL
              valueFrom:
                configMapKeyRef: 
                  name:  configmap-book-catalog
                  key: spring.datasource.url

            - name: DATASOURCEUSERNAME
              valueFrom:
                configMapKeyRef: 
                  name:  configmap-book-catalog
                  key: spring.datasource.username

            - name: DATASOURCEPASSWORD
              valueFrom:
                configMapKeyRef: 
                  name:  configmap-book-catalog
                  key: spring.datasource.password

            - name: DATASOURCEDRIVERCLASS
              valueFrom:
                configMapKeyRef: 
                  name:  configmap-book-catalog
                  key: spring.datasource.driver-class-name

            - name: HIBERNATEDDLAUTO
              valueFrom:
                configMapKeyRef: 
                  name: configmap-book-catalog
                  key: spring.jpa.hibernate.ddl-auto

            - name: HIBERNATESHOWSQL
              valueFrom:
                configMapKeyRef: 
                  name:  configmap-book-catalog
                  key: spring.jpa.show-sql

            - name: HIBERNATEDIALECT
              valueFrom:
                configMapKeyRef: 
                  name:  configmap-book-catalog
                  key: spring.jpa.properties.hibernate.dialect

            - name: APPLICATIONNAME
              valueFrom:
                configMapKeyRef: 
                  name:  configmap-book-catalog
                  key: application.name

            - name: SERVERPORT
              valueFrom:
                configMapKeyRef: 
                  name:  configmap-book-catalog
                  key: server.port
            

          volumeMounts:
            - name: configmap-book-catalog-volume
              readOnly: true
              mountPath: "/config/configmap-book-catalog" 
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: configmap-book-catalog
data:
  server.port: "0"
  application.name: "bookcatalog"
  spring.datasource.url: "jdbc:mysql://mysql-service.default.svc.cluster.local:3306/test"
  spring.datasource.username: "root"
  spring.datasource.password: "1234"
  spring.datasource.driver-class-name: "com.mysql.cj.jdbc.Driver"
  spring.jpa.hibernate.ddl-auto: "create-drop"
  spring.jpa.show-sql: "true"
  spring.jpa.properties.hibernate.dialect: "org.hibernate.dialect.MariaDBDialect"




